apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-chatting
spec:
  selector:
    matchLabels:
      app: chatting
  replicas: 1
  template:
    metadata:
      labels:
        app: chatting
    spec:
      containers:
        - name: chattingapp
          image: 211125685751.dkr.ecr.ap-northeast-2.amazonaws.com/woorizip-chatting:20240508203715
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-chatting
spec:
  selector:
    app: chatting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort