apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-chatting
spec:
  selector:
    matchLabels:
      app: chattingapp
  replicas: 1
  template:
    metadata:
      labels:
        app: chattingapp
    spec:
      containers:
      - name: chatting
        image: 211125685751.dkr.ecr.ap-northeast-2.amazonaws.com/woorizip-chatting:20240502022359
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-chatting
spec:
  selector:
    app: chattingapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
