server:
  port: 8080

spring:
  cloud.vault:
    host: testaws.teamwaf.app
    token: hvs.moFEi0WpVCrsTtEyWBsjscah
    scheme: http
    kv:
      enabled: true
    authentication: token

  data:
    redis:
      host: testaws.teamwaf.app
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://testaws.teamwaf.app:3306/teamwafdb?useUnicode=true&serverTimezone=Asia/Seoul
    username: teamwaf
    password: dntmdrhkaudtjd12
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    show-sql: true
  rabbitmq:
    username: guest
    password: guest
    host: testaws.teamwaf.app
    port: 5672
rabbitmq:
  stomp-port: 61613
  endpoint: /stomp/chat
  queue.name: chat.queue
  exchange.name: chat.exchange
  routing.key: room.*

grpc:
  client:
#    auth-server:
#      address: 'static://localhost:50052'
#      negotiation-type: plaintext
    account-server:
      address: 'static://localhost:4000'
      negotiation-type: plaintext


amazon:
  dynamodb:
    endpoint: dynamodb.ap-northeast-2.amazonaws.com
  aws:
    accesskey: AKIATCKASJX3SN66FXO2
    secretkey: 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
